;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	crux-kill-whole-line
	crux-move-beginning-of-line
	crux-smart-open-line
	crux-smart-open-line-above
	helm-M-x
	helm-show-kill-ring
	hydra-multiple-cursors/body
	kill-region
	kill-sexp
	mark-sexp
	web-mode-element-vanish
	))

(setq mc/cmds-to-run-once
      '(
	helm-swoop
	hydra-multiple-cursors/mc/edit-lines-and-exit
	hydra-multiple-cursors/mc/mark-all-like-this-and-exit
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/mc/mark-previous-like-this
	hydra-multiple-cursors/mc/skip-to-next-like-this
	hydra-window/windmove-up
	multiple-cursors-hydra/*
	multiple-cursors-hydra/body
	))
